### ISSUE TITLE
TODO/FIXME Count 7

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mail#8]
- [ ] FIXME: what to log? what level? seperate mail log? event?
       Commit: (b423b0a) Add more logging options.
       File:  [lib/index.js:251](https://github.com/digitalbazaar/bedrock-mail/blob/master/lib/index.js#L251)
       David I. Lehn commented 4 months ago

  - [ ] FIXME: add original email in header?
       Commit: (271faa9) Add FIXME.
       File:  [lib/index.js:242](https://github.com/digitalbazaar/bedrock-mail/blob/master/lib/index.js#L242)
       David I. Lehn commented 4 months ago

  - [ ] FIXME: shallow? deep? let caller do it?
       Commit: (8531146) Update deps, modernize, and change everything.
       File:  [lib/index.js:238](https://github.com/digitalbazaar/bedrock-mail/blob/master/lib/index.js#L238)
       David I. Lehn commented 4 months ago

  - [ ] FIXME: add custom config.mail.templates.paths multi-path template lookup
       Commit: (8531146) Update deps, modernize, and change everything.
       File:  [lib/index.js:236](https://github.com/digitalbazaar/bedrock-mail/blob/master/lib/index.js#L236)
       David I. Lehn commented 4 months ago

  - [ ] FIXME: log warning?
       Commit: (3cbe3b5) Add use() and verify() APIs.
       File:  [lib/index.js:233](https://github.com/digitalbazaar/bedrock-mail/blob/master/lib/index.js#L233)
       David I. Lehn commented 4 months ago

  - [ ] FIXME: allow changing template engine
       Commit: (8531146) Update deps, modernize, and change everything.
       File:  [lib/index.js:161](https://github.com/digitalbazaar/bedrock-mail/blob/master/lib/index.js#L161)
       David I. Lehn commented 4 months ago

  - [ ] FIXME: some default support already exists
       Commit: (8531146) Update deps, modernize, and change everything.
       File:  [lib/config.js:34](https://github.com/digitalbazaar/bedrock-mail/blob/master/lib/config.js#L34)
       David I. Lehn commented 4 months ago
